from __future__ import annotations
from typing import Protocol
from ishworkzero.domain.models import Case
class CaseStore(Protocol):
    def put(self,case:Case)->None: ...
    def get(self,case_id:str,tenant_id:str|None=None)->Case: ...
    def list(self,tenant_id:str)->list[Case]: ...
